
spring:
  profiles:
    active:
    - prod
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

logistics:
  limits:
    30: 1
    60: 2
    120: 5.3


logging.level.org.springframework.security: DEBUG
